#!/bin/bash

if [ "`id pidgeonsv | wc -l`" -eq 0 ];then
	echo "Creating a service account for pidgeon services"
	useradd -r pidgeonsv -d /usr/share/pidgeon-sv || exit 1
fi

if [ ! -d "/usr/share/pidgeon-sv" ];then
  mkdir /usr/share/pidgeon-sv
fi

if [ ! -d "/usr/share/pidgeon-sv/data" ];then
	mkdir "/usr/share/pidgeon-sv/data" || exit 1
fi

if [ ! -d "/usr/share/pidgeon-sv/db" ];then
	mkdir "/usr/share/pidgeon-sv/db" || exit 1
fi

if [ ! -d "/var/log/pidgeon-sv" ];then
    mkdir "/var/log/pidgeon-sv"
fi

chown -R pidgeonsv "/var/log/pidgeon-sv"

chown -R pidgeonsv "/usr/share/pidgeon-sv/"
ln -s /etc/pidgeon-sv/pidgeon-sv.conf /usr/share/pidgeon-sv/pidgeon.conf
touch /var/log/pidgeonsv.log
chown pidgeonsv /var/log/pidgeonsv.log

exit 0
