#!/bin/bash

if [ "`id pidgeonsv | wc -l`" -eq 0 ];then
	echo "Creating a service account for pidgeon services"
	useradd -r pidgeonsv -d /usr/share/pidgeonsv || exit 1
fi

if [ ! -d "/usr/share/pidgeonsv" ];then
  mkdir /usr/share/pidgeonsv
fi

if [ ! -d "/usr/share/pidgeonsv/data" ];then
	mkdir "/usr/share/pidgeonsv/data" || exit 1
fi

if [ ! -d "/usr/share/pidgeonsv/db" ];then
	mkdir "/usr/share/pidgeonsv/db" || exit 1
fi

chown -R pidgeonsv "/usr/share/pidgeon-sv/"
ln -s /etc/pidgeon-sv/pidgeon-sv.conf /usr/share/pidgeon-sv/pidgeon.conf
touch /var/log/pidgeonsv.log
chown pidgeonsv /var/log/pidgeonsv.log

exit 0
